### ISSUE TITLE
This app isn't working properly

### ISSUE THREAD

**Issue by creativeworks27** [VirgilSecurity/chat-back4app-android#5]
App builds and runs, it lets me create test users but it crashes when i select a user and try to send a message, throwing this error (VirgilCard not Found) then tried uploading the main.js with credentials from Virgil Account as well as package.json file to the Back4app cloud services and app build and runs but this time doesn't let me create new users and throws and error ("Oops.. Something went wrong ):") witch is coming from the resolveError(Throwable t) method.

**Comment by BuddahLD** [comment]
Hi, @creativeworks27 ! Sorry to hear that!
I'll check the sample and get back to you in a few hours!
Back4app having issues with cloud code, so it can be the issue.
Thank you for the feedback!

**Comment by BuddahLD** [comment]
@creativeworks27 I've reviewed demo and contacted Back4App team, it's Back4App side issue indeed. A ticket has been opened for this issue with cloud code. Sorry but we cannot do a lot till they fix cloud code. 
Will notify you once the ticket is closed and the issue is resolved.

**Comment by creativeworks27** [comment]
Can't wait to see it solved :) , thank you very much for you quick response.

**Comment by mostafa-elkhouly96** [comment]
what about the virgil site ?

**Comment by BuddahLD** [comment]
what do you mean? can you specify your question, please?

**Comment by mostafa-elkhouly96** [comment]
can you open the dashboard and try to create a new application on virgil website ?
they change the encryption on it !

**Comment by BuddahLD** [comment]
this question is not related to back4app, please open new issue or contact Virgil Security support.
Thank you!

@creativeworks27 I'm closing the issue but feel free to open/reopen the issue if it still exists!
