### ISSUE TITLE
A question !

### ISSUE THREAD

**Issue by mostafa-elkhouly96** [VirgilSecurity/chat-back4app-android#8]
What is the encryption technique used here ?!
Is that secure enough?

**Comment by BuddahLD** [comment]
Hi, @mostafa-elkhouly96 !
Yes sure it's secure enough!
You can read about our crypto via link:
https://github.com/VirgilSecurity/virgil-crypto-c#library-foundation

Please, contact our support for such kind of questions, instead of issues on github!
Thank you!
